/**
 * World layout schema v1 — positions every map in one shared, signed-integer global tile
 * coordinate space (`src/data/maps/world.json`), plus the generated manifest seam (plan 014 step
 * 1). Pure — no Phaser; imports only types + a couple of pure helpers from `mapFormat.ts` (the
 * same choke-point pattern, one level up: map-local shape/walkability data feeds cross-map
 * validation here).
 *
 * "Which map owns global tile (c,r)" is always a DERIVED index (`buildWorldIndex`), never stored
 * — dragging a map in the world view only ever edits `world.json`'s placements, so map JSON diffs
 * never churn. This module is the global-coordinate seam future cross-map AI (monster chases
 * across map boundaries) paths through — keep additions engine-agnostic.
 *
 * Generated-manifest shape (`src/data/maps/manifest.json`, regenerated by the editor's save
 * middleware on every save — hand-editing is forbidden, same as cells arrays): kept trivially
 * simple on purpose — `{ schemaVersion, placements, maps: [{id,name,width,height}] }` — a plain
 * merge of `world.json`'s placements with each map's meta, so a game-side eager import gets
 * everything `mapAt`'s bbox pre-filter needs without loading a single map file.
 */

import { getCell, isInside, type MapFile } from './mapFormat';

// ---- Types (world layout schema v1) ----

export interface MapPlacement {
  mapId: string;
  /** Signed integer global tile coords of this map's local (0,0). */
  origin: { col: number; row: number };
}

export interface WorldLayout {
  schemaVersion: 1;
  placements: MapPlacement[];
}

/** Just enough of a map's meta for the bbox pre-filter — lets `mapAt` answer from the manifest
 *  alone, with no map file loaded. */
export interface MapMetaLite {
  id: string;
  width: number;
  height: number;
}

export interface ManifestMapEntry {
  id: string;
  name: string;
  width: number;
  height: number;
}

/** See module doc for the deliberately-trivial shape. */
export interface MapManifest {
  schemaVersion: 1;
  placements: MapPlacement[];
  maps: ManifestMapEntry[];
}

export interface WorldValidation {
  errors: string[];
  warnings: string[];
}

export interface SeamCellPair {
  /** Cell local to the queried map. */
  a: { col: number; row: number };
  /** The corresponding cell in the adjacent neighbour map, local to that neighbour. */
  b: { mapId: string; col: number; row: number };
}

export interface WorldIndex {
  /** Resolves the map owning global tile `(gcol,grow)`, or `null` if unowned. Bbox pre-filters
   *  from the metas supplied at construction; does an exact shape-mask check only for maps also
   *  present in the optional `maps` record (falls back to a bbox-only answer for a candidate
   *  whose map isn't loaded — see `buildWorldIndex`). */
  mapAt(gcol: number, grow: number): string | null;
  /** Derived adjacent-edge cell pairs between `mapId` and its placed neighbours. Requires `mapId`
   *  and its neighbours to be in the `maps` record passed to `buildWorldIndex`; returns `[]`
   *  otherwise (can't derive seams from bbox metas alone). */
  seams(mapId: string): SeamCellPair[];
}

// ---- Coordinate helpers ----

export function localToGlobal(
  origin: { col: number; row: number },
  col: number,
  row: number,
): { col: number; row: number } {
  return { col: origin.col + col, row: origin.row + row };
}

export function globalToLocal(
  origin: { col: number; row: number },
  gcol: number,
  grow: number,
): { col: number; row: number } {
  return { col: gcol - origin.col, row: grow - origin.row };
}

/** Convenience for building the `metas` argument `buildWorldIndex` wants from full `MapFile`s
 *  (tests / callers that already have the whole map loaded). */
export function metasFromMaps(maps: Record<string, MapFile>): Record<string, MapMetaLite> {
  const metas: Record<string, MapMetaLite> = {};
  for (const [id, map] of Object.entries(maps)) {
    metas[id] = { id, width: map.meta.width, height: map.meta.height };
  }
  return metas;
}

// ---- Parsing helpers (throw with a precise `<path> <problem>` message) ----

function fail(message: string): never {
  throw new Error(message);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function expectRecord(value: unknown, path: string): Record<string, unknown> {
  if (!isRecord(value)) fail(`${path} must be an object`);
  return value;
}

function expectString(value: unknown, path: string): string {
  if (typeof value !== 'string') fail(`${path} must be a string`);
  return value;
}

function expectInt(value: unknown, path: string): number {
  if (typeof value !== 'number' || !Number.isFinite(value) || !Number.isInteger(value)) {
    fail(`${path} must be an integer`);
  }
  return value;
}

function expectArray(value: unknown, path: string): unknown[] {
  if (!Array.isArray(value)) fail(`${path} must be an array`);
  return value;
}

function parsePlacement(value: unknown, path: string): MapPlacement {
  const obj = expectRecord(value, path);
  const originObj = expectRecord(obj.origin, `${path}.origin`);
  return {
    mapId: expectString(obj.mapId, `${path}.mapId`),
    origin: {
      col: expectInt(originObj.col, `${path}.origin.col`),
      row: expectInt(originObj.row, `${path}.origin.row`),
    },
  };
}

// ---- Public API: world.json ----

/** Validate + narrow an unknown JSON value into a `WorldLayout`. Throws with a precise message on
 *  the first violation. */
export function parseWorldLayout(json: unknown): WorldLayout {
  const root = expectRecord(json, 'world');
  const schemaVersion = expectInt(root.schemaVersion, 'world.schemaVersion');
  if (schemaVersion !== 1) fail(`world.schemaVersion ${schemaVersion} is not supported`);

  const placementsRaw = expectArray(root.placements, 'world.placements');
  const placements = placementsRaw.map((p, i) => parsePlacement(p, `world.placements[${i}]`));

  const seen = new Set<string>();
  for (const p of placements) {
    if (seen.has(p.mapId)) fail(`world.placements has a duplicate placement for map "${p.mapId}"`);
    seen.add(p.mapId);
  }

  return { schemaVersion: 1, placements };
}

// ---- Cross-map validation ----

interface PairRelation {
  overlapAt: { col: number; row: number } | null;
  edgeAdjacent: boolean;
  diagonalAdjacent: boolean;
  mismatches: Array<{ col: number; row: number }>;
}

const ORTHOGONAL: ReadonlyArray<readonly [number, number]> = [
  [1, 0],
  [-1, 0],
  [0, 1],
  [0, -1],
];
const DIAGONAL: ReadonlyArray<readonly [number, number]> = [
  [1, 1],
  [1, -1],
  [-1, 1],
  [-1, -1],
];

/**
 * Walks every inside cell of `mapA` (placed at `a.origin`) and compares it against `mapB` (placed
 * at `b.origin`) in shared global coords: whether any inside cell overlaps, whether the two maps
 * share an actual orthogonal or only-diagonal edge, and — for every walkable edge cell of `mapA` —
 * whether the orthogonally-facing cell in `mapB`'s territory is void or blocked (a seam
 * mismatch). One-directional (A's walkable cells facing B); callers run it both ways to get full
 * coverage of a pair.
 */
function computePairRelation(
  a: MapPlacement,
  mapA: MapFile,
  b: MapPlacement,
  mapB: MapFile,
): PairRelation {
  let overlapAt: { col: number; row: number } | null = null;
  let edgeAdjacent = false;
  let diagonalAdjacent = false;
  const mismatches: Array<{ col: number; row: number }> = [];

  const { width: widthA, height: heightA } = mapA.meta;
  const { width: widthB, height: heightB } = mapB.meta;

  const inBoundsB = (col: number, row: number): boolean =>
    col >= 0 && col < widthB && row >= 0 && row < heightB;

  for (let row = 0; row < heightA; row++) {
    for (let col = 0; col < widthA; col++) {
      if (!isInside(mapA, col, row)) continue;
      const g = localToGlobal(a.origin, col, row);
      const lb = globalToLocal(b.origin, g.col, g.row);

      if (!overlapAt && inBoundsB(lb.col, lb.row) && isInside(mapB, lb.col, lb.row)) {
        overlapAt = g;
      }

      const aWalkable = getCell(mapA.walkability.cells, col, row, widthA) === 0;

      for (const [dc, dr] of ORTHOGONAL) {
        const nlb = globalToLocal(b.origin, g.col + dc, g.row + dr);
        if (!inBoundsB(nlb.col, nlb.row)) continue;
        const bInside = isInside(mapB, nlb.col, nlb.row);
        if (bInside) edgeAdjacent = true;
        if (aWalkable) {
          const bBlocked =
            bInside && getCell(mapB.walkability.cells, nlb.col, nlb.row, widthB) === 1;
          if (!bInside || bBlocked) mismatches.push(g);
        }
      }

      for (const [dc, dr] of DIAGONAL) {
        const nlb = globalToLocal(b.origin, g.col + dc, g.row + dr);
        if (inBoundsB(nlb.col, nlb.row) && isInside(mapB, nlb.col, nlb.row))
          diagonalAdjacent = true;
      }
    }
  }

  return { overlapAt, edgeAdjacent, diagonalAdjacent, mismatches };
}

/**
 * ERROR = a placement referencing an unknown map, or two placed maps' inside cells overlapping in
 * world space (ownership uniqueness — the one thing streaming cannot tolerate). WARNING = seam
 * walkability mismatch, diagonal-only adjacency, an island map (no neighbours), or a map missing
 * from `world.json` (unplaced/dev map). Only errors should fail a load; warnings surface as editor
 * badges. `maps` must contain every map referenced by `layout.placements` for a full check — an
 * unknown mapId is reported as an error and that placement is excluded from the rest of the pass.
 */
export function validateWorld(layout: WorldLayout, maps: Record<string, MapFile>): WorldValidation {
  const errors: string[] = [];
  const warnings: string[] = [];

  const validPlacements: MapPlacement[] = [];
  for (const placement of layout.placements) {
    if (!maps[placement.mapId]) {
      errors.push(`placement references unknown map "${placement.mapId}"`);
      continue;
    }
    validPlacements.push(placement);
  }

  const neighbourCount = new Map<string, number>(validPlacements.map((p) => [p.mapId, 0]));

  for (let i = 0; i < validPlacements.length; i++) {
    for (let j = i + 1; j < validPlacements.length; j++) {
      const a = validPlacements[i];
      const b = validPlacements[j];
      const mapA = maps[a.mapId];
      const mapB = maps[b.mapId];
      const ab = computePairRelation(a, mapA, b, mapB);
      const ba = computePairRelation(b, mapB, a, mapA);

      if (ab.overlapAt) {
        errors.push(
          `maps "${a.mapId}" and "${b.mapId}" overlap at global tile (${ab.overlapAt.col},${ab.overlapAt.row})`,
        );
      }

      const edgeAdjacent = ab.edgeAdjacent || ba.edgeAdjacent;
      const diagonalAdjacent = ab.diagonalAdjacent || ba.diagonalAdjacent;
      if (edgeAdjacent || diagonalAdjacent) {
        neighbourCount.set(a.mapId, (neighbourCount.get(a.mapId) ?? 0) + 1);
        neighbourCount.set(b.mapId, (neighbourCount.get(b.mapId) ?? 0) + 1);
      }
      if (!edgeAdjacent && diagonalAdjacent) {
        warnings.push(`maps "${a.mapId}" and "${b.mapId}" are only diagonally adjacent`);
      }

      const mismatchCount = ab.mismatches.length + ba.mismatches.length;
      if (mismatchCount > 0) {
        warnings.push(
          `seam walkability mismatch between "${a.mapId}" and "${b.mapId}" ` +
            `(${mismatchCount} cell${mismatchCount === 1 ? '' : 's'})`,
        );
      }
    }
  }

  for (const p of validPlacements) {
    if ((neighbourCount.get(p.mapId) ?? 0) === 0) {
      warnings.push(`map "${p.mapId}" has no neighbours (island)`);
    }
  }

  const placedIds = new Set(layout.placements.map((p) => p.mapId));
  for (const id of Object.keys(maps)) {
    if (!placedIds.has(id)) warnings.push(`map "${id}" is not placed in world.json`);
  }

  return { errors, warnings };
}

// ---- Derived world index ----

/**
 * Builds the derived "who owns this global tile" + "what touches this map's edge" index. `metas`
 * drives the cheap bbox pre-filter (works from the manifest alone, no map files loaded); the
 * optional `maps` record upgrades `mapAt` to an exact shape-mask check for whichever maps are
 * supplied, and is required for `seams` to return anything.
 */
export function buildWorldIndex(
  placements: MapPlacement[],
  metas: Record<string, MapMetaLite>,
  maps?: Record<string, MapFile>,
): WorldIndex {
  function bboxCandidates(gcol: number, grow: number): MapPlacement[] {
    return placements.filter((p) => {
      const meta = metas[p.mapId];
      if (!meta) return false;
      return (
        gcol >= p.origin.col &&
        gcol < p.origin.col + meta.width &&
        grow >= p.origin.row &&
        grow < p.origin.row + meta.height
      );
    });
  }

  function mapAt(gcol: number, grow: number): string | null {
    const candidates = bboxCandidates(gcol, grow);
    if (candidates.length === 0) return null;

    // Prefer an exact shape-mask match among loaded maps.
    for (const p of candidates) {
      const map = maps?.[p.mapId];
      if (!map) continue;
      const local = globalToLocal(p.origin, gcol, grow);
      if (isInside(map, local.col, local.row)) return p.mapId;
    }

    // Fall back to a bbox-only match for a candidate whose map isn't loaded.
    for (const p of candidates) {
      if (!maps?.[p.mapId]) return p.mapId;
    }

    return null;
  }

  function seams(mapId: string): SeamCellPair[] {
    const placement = placements.find((p) => p.mapId === mapId);
    const map = maps?.[mapId];
    if (!placement || !map) return [];

    const result: SeamCellPair[] = [];
    for (let row = 0; row < map.meta.height; row++) {
      for (let col = 0; col < map.meta.width; col++) {
        if (!isInside(map, col, row)) continue;
        const g = localToGlobal(placement.origin, col, row);
        for (const [dc, dr] of ORTHOGONAL) {
          const ngcol = g.col + dc;
          const ngrow = g.row + dr;
          for (const other of placements) {
            if (other.mapId === mapId) continue;
            const otherMap = maps?.[other.mapId];
            if (!otherMap) continue;
            const local = globalToLocal(other.origin, ngcol, ngrow);
            if (isInside(otherMap, local.col, local.row)) {
              result.push({ a: { col, row }, b: { mapId: other.mapId, ...local } });
            }
          }
        }
      }
    }
    return result;
  }

  return { mapAt, seams };
}

// ---- Manifest (generated artifact — parsing + the pure generator) ----

function parseManifestMapEntry(value: unknown, path: string): ManifestMapEntry {
  const obj = expectRecord(value, path);
  const width = expectInt(obj.width, `${path}.width`);
  const height = expectInt(obj.height, `${path}.height`);
  if (width <= 0) fail(`${path}.width must be > 0`);
  if (height <= 0) fail(`${path}.height must be > 0`);
  return {
    id: expectString(obj.id, `${path}.id`),
    name: expectString(obj.name, `${path}.name`),
    width,
    height,
  };
}

/** Validate + narrow an unknown JSON value into a `MapManifest`. Throws with a precise message on
 *  the first violation. */
export function parseManifest(json: unknown): MapManifest {
  const root = expectRecord(json, 'manifest');
  const schemaVersion = expectInt(root.schemaVersion, 'manifest.schemaVersion');
  if (schemaVersion !== 1) fail(`manifest.schemaVersion ${schemaVersion} is not supported`);

  const placementsRaw = expectArray(root.placements, 'manifest.placements');
  const placements = placementsRaw.map((p, i) => parsePlacement(p, `manifest.placements[${i}]`));

  const mapsRaw = expectArray(root.maps, 'manifest.maps');
  const mapEntries = mapsRaw.map((m, i) => parseManifestMapEntry(m, `manifest.maps[${i}]`));
  const seen = new Set<string>();
  for (const m of mapEntries) {
    if (seen.has(m.id)) fail(`manifest.maps has a duplicate id "${m.id}"`);
    seen.add(m.id);
  }

  return { schemaVersion: 1, placements, maps: mapEntries };
}

/**
 * Pure re-implementation of what the editor's save middleware regenerates on every map/world save
 * (plain JS there; this version serves tests + the DEV load-time consistency assertion). Sorted by
 * id for a deterministic, diff-friendly output regardless of input order.
 */
export function generateManifest(world: WorldLayout, maps: Record<string, MapFile>): MapManifest {
  const placements = [...world.placements].sort((a, b) => a.mapId.localeCompare(b.mapId));
  const mapEntries: ManifestMapEntry[] = Object.keys(maps)
    .sort((a, b) => a.localeCompare(b))
    .map((id) => {
      const map = maps[id];
      return {
        id: map.meta.id,
        name: map.meta.name,
        width: map.meta.width,
        height: map.meta.height,
      };
    });
  return { schemaVersion: 1, placements, maps: mapEntries };
}
